// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Delegate.Daxif.Scripts")>]
[<assembly: AssemblyProductAttribute("Delegate.Daxif.Scripts")>]
[<assembly: AssemblyDescriptionAttribute("Example Scripts for Daxif. Delegate Automated xRM Installation Framework")>]
[<assembly: AssemblyCompanyAttribute("Delegate")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2017")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Delegate.Daxif.Scripts"
    let [<Literal>] AssemblyProduct = "Delegate.Daxif.Scripts"
    let [<Literal>] AssemblyDescription = "Example Scripts for Daxif. Delegate Automated xRM Installation Framework"
    let [<Literal>] AssemblyCompany = "Delegate"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2017"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
