// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Delegate.Daxif.Scripts")]
[assembly: AssemblyProduct("Delegate.Daxif.Scripts")]
[assembly: AssemblyDescription("Example Scripts for Daxif. Delegate Automated xRM Installation Framework")]
[assembly: AssemblyCompany("Delegate")]
[assembly: AssemblyCopyright("Copyright (c) Delegate A/S 2017")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Delegate.Daxif.Scripts";
        internal const System.String AssemblyProduct = "Delegate.Daxif.Scripts";
        internal const System.String AssemblyDescription = "Example Scripts for Daxif. Delegate Automated xRM Installation Framework";
        internal const System.String AssemblyCompany = "Delegate";
        internal const System.String AssemblyCopyright = "Copyright (c) Delegate A/S 2017";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
    }
}
