image: Visual Studio 2019
configuration: Release
before_build:
  - nuget restore "src"

assembly_info:
  patch: true
  file: src\Delegate.Daxif\AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: src\Delegate.Daxif.sln