// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Delegate.Daxif")>]
[<assembly: AssemblyProductAttribute("Delegate.Daxif")>]
[<assembly: AssemblyDescriptionAttribute("Delegate Automated xRM Installation Framework")>]
[<assembly: AssemblyCompanyAttribute("Delegate")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Delegate A/S 2017")>]
[<assembly: AssemblyVersionAttribute("3.1.5")>]
[<assembly: AssemblyFileVersionAttribute("3.1.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Delegate.Daxif"
    let [<Literal>] AssemblyProduct = "Delegate.Daxif"
    let [<Literal>] AssemblyDescription = "Delegate Automated xRM Installation Framework"
    let [<Literal>] AssemblyCompany = "Delegate"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Delegate A/S 2017"
    let [<Literal>] AssemblyVersion = "3.1.5"
    let [<Literal>] AssemblyFileVersion = "3.1.5"
